import os

from neurosap import actions

pet_dir = "images/pets/"
food_dir = "images/foods/"
pet_index = [f[:-4] for f in sorted(os.listdir(pet_dir))]
food_index = [f[:-4] for f in sorted(os.listdir(food_dir))]

encoding_index = [
    "coins",
    "lives",
    "trophies",
    "turn",
    "t0_pet_id",
    "t0_att",
    "t0_hp",
    "t0_item_id",
    "t0_lvl",
    "t0_exp",
    "t1_pet_id",
    "t1_att",
    "t1_hp",
    "t1_item_id",
    "t1_lvl",
    "t1_exp",
    "t2_pet_id",
    "t2_att",
    "t2_hp",
    "t2_item_id",
    "t2_lvl",
    "t2_exp",
    "t3_pet_id",
    "t3_att",
    "t3_hp",
    "t3_item_id",
    "t3_lvl",
    "t3_exp",
    "t4_pet_id",
    "t4_att",
    "t4_hp",
    "t4_item_id",
    "t4_lvl",
    "t4_exp",
    "s0_pet_id",  # 34
    "s0_att",
    "s0_hp",
    "s1_pet_id",
    "s1_att",
    "s1_hp",
    "s2_pet_id",
    "s2_att",
    "s2_hp",
    "s3_pet_id",
    "s3_att",
    "s3_hp",
    "s4_pet_id",
    "s4_att",
    "s4_hp",
    "f0_item_id",
    "f1_item_id",
]

decoding_index = [
    actions.t0_to_t1,
    actions.t0_to_t2,
    actions.t0_to_t3,
    actions.t0_to_t4,
    actions.t1_to_t0,
    actions.t1_to_t2,
    actions.t1_to_t3,
    actions.t1_to_t4,
    actions.t2_to_t0,
    actions.t2_to_t1,
    actions.t2_to_t3,
    actions.t2_to_t4,
    actions.t3_to_t0,
    actions.t3_to_t1,
    actions.t3_to_t2,
    actions.t3_to_t4,
    actions.t4_to_t0,
    actions.t4_to_t1,
    actions.t4_to_t2,
    actions.t4_to_t3,
    actions.s0_to_t0,  # 20
    actions.s0_to_t1,
    actions.s0_to_t2,
    actions.s0_to_t3,
    actions.s0_to_t4,
    actions.s1_to_t0,
    actions.s1_to_t1,
    actions.s1_to_t2,
    actions.s1_to_t3,
    actions.s1_to_t4,
    actions.s2_to_t0,
    actions.s2_to_t1,
    actions.s2_to_t2,
    actions.s2_to_t3,
    actions.s2_to_t4,
    actions.s3_to_t0,
    actions.s3_to_t1,
    actions.s3_to_t2,
    actions.s3_to_t3,
    actions.s3_to_t4,
    actions.s4_to_t0,
    actions.s4_to_t1,
    actions.s4_to_t2,
    actions.s4_to_t3,
    actions.s4_to_t4,
    actions.f0_to_t0,  # 45
    actions.f0_to_t1,
    actions.f0_to_t2,
    actions.f0_to_t3,
    actions.f0_to_t4,
    actions.f1_to_t0,  # 50
    actions.f1_to_t1,
    actions.f1_to_t2,
    actions.f1_to_t3,
    actions.f1_to_t4,
    actions.sell_t0,  # 55
    actions.sell_t1,
    actions.sell_t2,
    actions.sell_t3,
    actions.sell_t4,
    actions.roll,
    actions.end,
]

decoding_str_index = [
    "Team 0 to Team 1",
    "Team 0 to Team 2",
    "Team 0 to Team 3",
    "Team 0 to Team 4",
    "Team 1 to Team 0",
    "Team 1 to Team 2",
    "Team 1 to Team 3",
    "Team 1 to Team 4",
    "Team 2 to Team 0",
    "Team 2 to Team 1",
    "Team 2 to Team 3",
    "Team 2 to Team 4",
    "Team 3 to Team 0",
    "Team 3 to Team 1",
    "Team 3 to Team 2",
    "Team 3 to Team 4",
    "Team 4 to Team 0",
    "Team 4 to Team 1",
    "Team 4 to Team 2",
    "Team 4 to Team 3",
    "Shop 0 to Team 0",  # 20
    "Shop 0 to Team 1",
    "Shop 0 to Team 2",
    "Shop 0 to Team 3",
    "Shop 0 to Team 4",
    "Shop 1 to Team 0",
    "Shop 1 to Team 1",
    "Shop 1 to Team 2",
    "Shop 1 to Team 3",
    "Shop 1 to Team 4",
    "Shop 2 to Team 0",
    "Shop 2 to Team 1",
    "Shop 2 to Team 2",
    "Shop 2 to Team 3",
    "Shop 2 to Team 4",
    "Shop 3 to Team 0",
    "Shop 3 to Team 1",
    "Shop 3 to Team 2",
    "Shop 3 to Team 3",
    "Shop 3 to Team 4",
    "Shop 4 to Team 0",
    "Shop 4 to Team 1",
    "Shop 4 to Team 2",
    "Shop 4 to Team 3",
    "Shop 4 to Team 4",
    "Food 0 to Team 0",  # 45
    "Food 0 to Team 1",
    "Food 0 to Team 2",
    "Food 0 to Team 3",
    "Food 0 to Team 4",
    "Food 1 to Team 0",  # 50
    "Food 1 to Team 1",
    "Food 1 to Team 2",
    "Food 1 to Team 3",
    "Food 1 to Team 4",
    "Sell Team 0",  # 55
    "Sell Team 1",
    "Sell Team 2",
    "Sell Team 3",
    "Sell Team 4",
    "Roll",
    "End Turn",
]


threshold_overrides = {
    "ant": 0.21,
    "badger": 0.18,
    "bison": 0.18,
    "deer": 0.22,
    "dodo": 0.19,
    "dog": 0.2,
    "elephant": 0.28,
    "fish": 0.19,
    "giraffe": 0.15,
    "hippo": 0.2,
    "kangaroo": 0.2,
    "mammoth": 0.23,
    "monkey": 0.13,
    "parrot": 0.22,
    "peacock": 0.25,
    "penguin": 0.25,
    "rat": 0.25,
    "rhino": 0.24,
    "rooster": 0.22,
    "scorpion": 0.14,
    "shark": 0.25,
    "sheep": 0.16,
    "snail": 0.2,
    "snake": 0.2,
    "squirrel": 0.26,
    "swan": 0.2,
    "tiger": 0.24,
    "turtle": 0.17,
}
